### ISSUE TITLE
알라딘 eBook 5.1.8을 5.1.7로 업데이트하라고 표시됩니다

### ISSUE THREAD

**Issue by comiluv** [nerious2/SEM#1]
초기 화면에서 다음 스크린샷과 같이 5.1.8을 5.1.7로 업데이트하라고 표시되는데 이대로 업데이트하면 되는 건지 문의드립니다.
![Screenshot_20230711-010347](https://github.com/nerious2/SEM/assets/19642705/ae686571-b50f-447d-96d0-ec604b19bc36)
사용 기기는 오닉스 페이지
알라딘 eBook은 구글  플레이 스토어를 통해 설치한 버전입니다.
모두의이북 버전은 1.0.05입니다.

**Comment by nerious2** [comment]
기기에 설치된 버전이 모두의 이북 서버에 있는 버전보다 높으며, 현재 모두의 이북에서는 단순히 버전명이 다를 경우 업데이트가 필요한 것으로 판단하기 때문에 발생하는 문제입니다. 차기 버전에 버전 코드를 비교하여 업데이트를 판단하게끔 조치할 예정입니다.

**Comment by nerious2** [comment]
해당 내용을 반영한 1.0.06 버전을 릴리즈 하였습니다. 감사합니다.
